version: '3.8'

services:
  postgres:
    image: postgres:16.2 
    restart: always  
    environment:
      POSTGRES_DB: ${DB_DATABASE}  
      POSTGRES_USER: ${DB_USERNAME}  
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    ports:
      - '15432:5432'  
    volumes:
      - postgres-data:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4  
    restart: always  
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.org" 
      PGADMIN_DEFAULT_PASSWORD: "admin" 
    ports:
      - '8081:80'  
    depends_on:
      - postgres 

volumes:
  postgres-data: 
